site_name: Hongnan Gao's MLOps Documentation
site_url: https://gao-hongnan.github.io/gaohn-mlops-docs
nav:
  - Home: index.md
  # - About: about.md
  # - DSA: dsa_intro.md
  - DSA_1: dsa_intro.ipynb


repo_url: https://github.com/gao-hongnan/gaohn-mlops-docs
repo_name: MLops-docs

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://sg.linkedin.com/in/reighnss
    - icon: fontawesome/brands/github
      link: https://github.com/gao-hongnan
      name: gaohn
  generator: false # false if don't show made by materials

copyright: Copyright &copy; 2021-2022 Gao Hongnan

theme:
  name: material
  logo: assets/logo.png
  features:
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github-square

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true 

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - css/extra.css

plugins:
  - search
  - markdown-exec # https://pypi.org/project/markdown-exec/
  - mkdocs-jupyter: # https://github.com/danielfrg/mkdocs-jupyter
      execute: false
      include_source: True
  # - mknotebooks: # python 3.9 not supported https://github.com/greenape/mknotebooks
  #     execute: false
  # - pheasant
  # - mkdocstrings